services:
  poc-app1:
  
    image: poc-multi-transport-app-js:latest
    container_name: poc-multi-transport-app-js
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DATABASE=recipe_db
      - DB_HOST=localhost
      - DB_DIALECT=mysql
    ports:
      - 3000:3000

